// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddLinkCommandButton: typeof import('./src/components/MenuCommands/Link/AddLinkCommandButton.vue')['default']
    CodeViewCommandButton: typeof import('./src/components/MenuCommands/CodeViewCommandButton.vue')['default']
    ColorPopover: typeof import('./src/components/MenuCommands/ColorPopover.vue')['default']
    CommandButton: typeof import('./src/components/MenuCommands/CommandButton.vue')['default']
    CreateTablePopover: typeof import('./src/components/MenuCommands/TablePopover/CreateTablePopover.vue')['default']
    EditImageCommandButton: typeof import('./src/components/MenuCommands/Image/EditImageCommandButton.vue')['default']
    EditLinkCommandButton: typeof import('./src/components/MenuCommands/Link/EditLinkCommandButton.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElementTiptap: typeof import('./src/components/ElementTiptap.vue')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElUpload: typeof import('element-ui/lib/upload')['default']
    FontSizeDropdown: typeof import('./src/components/MenuCommands/FontSizeDropdown.vue')['default']
    FontTypeDropdown: typeof import('./src/components/MenuCommands/FontTypeDropdown.vue')['default']
    FullscreenCommandButton: typeof import('./src/components/MenuCommands/FullscreenCommandButton.vue')['default']
    HeadingDropdown: typeof import('./src/components/MenuCommands/HeadingDropdown.vue')['default']
    IframeCommandButton: typeof import('./src/components/MenuCommands/IframeCommandButton.vue')['default']
    ImageBubbleMenu: typeof import('./src/components/MenuBubble/ImageBubbleMenu.vue')['default']
    ImageDisplayCommandButton: typeof import('./src/components/MenuCommands/Image/ImageDisplayCommandButton.vue')['default']
    ImageView: typeof import('./src/components/ExtensionViews/ImageView.vue')['default']
    InsertImageCommandButton: typeof import('./src/components/MenuCommands/Image/InsertImageCommandButton.vue')['default']
    LineHeightDropdown: typeof import('./src/components/MenuCommands/LineHeightDropdown.vue')['default']
    LinkBubbleMenu: typeof import('./src/components/MenuBubble/LinkBubbleMenu.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar/index.vue')['default']
    MenuBubble: typeof import('./src/components/MenuBubble/index.vue')['default']
    OpenLinkCommandButton: typeof import('./src/components/MenuCommands/Link/OpenLinkCommandButton.vue')['default']
    PreviewCommandButton: typeof import('./src/components/MenuCommands/PreviewCommandButton.vue')['default']
    RemoveImageCommandButton: typeof import('./src/components/MenuCommands/Image/RemoveImageCommandButton.vue')['default']
    TablePopover: typeof import('./src/components/MenuCommands/TablePopover/index.vue')['default']
    TodoItemView: typeof import('./src/components/ExtensionViews/TodoItemView.vue')['default']
    UnlinkCommandButton: typeof import('./src/components/MenuCommands/Link/UnlinkCommandButton.vue')['default']
  }
}

export { }
